name: Node.js CI

on:
  push:
    branches: [ "feature/USS31002_SN" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cred-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

        
    - run: pwd
    - run: ls 
    - run: cp -r ./credstore_ui/* ./
    - run: ls 
    - run: npm install
    - run: npm run build --if-present
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./build/*"
        target: "/var/app"
        
         
  cred-deploy:
    name: CredStore Deploy to EC2
    runs-on: self-hosted
    needs: cred-build
    
    steps:
         - run: pwd ; cd ../.. ; ls ;sudo netstat -tuln | grep 3000 && sudo kill $(sudo lsof -t -i:3000) ;sleep 10;sudo yum install tmux -y ; sudo npm install -g serve ;  RUNNER_TRACKING_ID="" && tmux new-session -d -s serve-session 'serve -s build' 


 
  
         
